name: .NET
on: [ push, pull_request ]
jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: dotnet build -c Release
        
      - name: Test
        run: dotnet test -c Release --no-build -v normal
